### ISSUE TITLE
default selected multiple options

### ISSUE THREAD

**Issue by yasir095** [adityasharat/angular-chosen#1]
Hi, I like this pluging and trying to use it but I have a little issue. It does display data right and user can make selection which binds to angular model as well. But if I have lets say a form which is prefilled with default multiple values, then it doesn't work. I have tried something like this.

<select id="daySelector"
        chosen
        multiple
        option="arrayListDays"
        ng-model="defaultSelected"
        ng-options="value as value.name for (key , value)  in arrayListDays"></select>

and im my controller I got this array

$scope.arrayListDays = [
            {
                "name": "Sunday",
                    "abbr": "Sun"
            },
            {
                "name": "Monday",
                    "abbr": "Mon"
            },
            {
                "name": "Tuesday",
                    "abbr": "Tue"
            },
            {
                "name": "Wednesday",
                    "abbr": "Wed"
            },
            {
                "name": "Thursday",
                    "abbr": "Thu"
            },
            {
                "name": "Friday",
                    "abbr": "Fri"
            },
             {
                "name": "Saturday",
                    "abbr": "Sat"
            }
        ];

$scope.defaultListSelected = scope.arrayListDays[3];

with single select it does fine but when i supply multiple in select box it doesn't prefilled anything. Can you please have a look.
Thanks

**Comment by adityasharat** [comment]
`(key , value)` is ideal for an `object`, but `arrayListDays` is an `Array`; just use `value` .

``` html
<select chosen multiple
  options="arrayListDays"
  ng-model="defaultListSelected"
  ng-options="value as value.name for value in arrayListDays">
```

and if this is a multi-select then the value of `ng-model` must be an `Array`. Something like this

``` javascript
$scope.defaultListSelected = [ scope.arrayListDays[3], scope.arrayListDays[4] ];
```

in addition you should add a `track by` in `ng-options`.

``` html
<...
  ng-options="value as value.name for value in arrayListDays track by value.abbr"
 ...></select>
```

Let me know if this works.

**Comment by yasir095** [comment]
Thanks it worked great. I used it like u said with a bit of modification.

value as value.name for value in arrayListDays track by value.Id

Thanks

**Comment by adityasharat** [comment]
Closing this issue.
