### ISSUE TITLE
Work with complex objects

### ISSUE THREAD

**Issue by intensite** [adityasharat/angular-chosen#10]
Is it possible for angular-chosen to work with composed objects.

Given an array like this:
 ctrl.employee =       [{"Employee_id": 29, "Name": "John Smith", "Initials": "JS"},
                        {"Employee_id": 30, "Name": "John Dow", "Initials": "JD"},
                        {"Employee_id": 31, "Name": "Klark Kent", "Initials": "KK"},
                        {"Employee_id": 32, "Name": "Fred Flistone", "Initials": "FF"},
                        {"Employee_id": 33, "Name": "John Wick", "Initials": "JW"},
                        {"Employee_id": 34, "Name": "Gautier Patrick", "Initials": "PG"}];

Show the name property in the drop down section but use only the Initials in the "tag like" section.  See the attached manually modified image.
![chosen-initials](https://cloud.githubusercontent.com/assets/7981384/10405015/423601be-6ea4-11e5-9589-94ce42114393.png)

**Comment by adityasharat** [comment]
A simple answer would be no :(
You can't do it with the current implementation.
You might have to change the source in chosen to achieve this trick.

**Comment by adityasharat** [comment]
A simple answer would be no :(
You can't do it with the current implementation.
You might have to change the source in chosen to achieve this trick.

**Comment by adityasharat** [comment]
Closing the issue
