### ISSUE TITLE
set text for chosen no result.

### ISSUE THREAD

**Issue by yasir095** [adityasharat/angular-chosen#13]
Hi aditya,

Good work man. I have a little issue can you please guide. I can see in the library you got a function that can be called on no result but do have any thing that set text when there are no results. By default you can do this in standard chosen module but it wont work in your angular version of module.

$(".chosen-select").chosen({no_results_text: "Oops, nothing found!"}); 

Thanks
Yasir

**Comment by yasir095** [comment]
Manage to achieve this by adding few lines of code to this library, Incase if any one needs. had to add no_results_text in the chosen element below and get the value from iAttr. Code changes below:

noResultsText = (iAttr.noResultsText != null) ? iAttr.noResultsText : "no matching record found";

 iElm.chosen({
                    width: '100%',
                    max_selected_options: maxSelection,
                    disable_search_threshold: searchThreshold,
                    no_results_text: noResultsText,
                    search_contains: true
                });

now in the template I used no-results-text = "whatever message you want to specify in case of no results"

**Comment by adityasharat** [comment]
:+1:
