### ISSUE TITLE
Use within uib-tabset from AngularUI

### ISSUE THREAD

**Issue by jonathanboswell** [adityasharat/angular-chosen#15]
First off, love the directive! Trying to use it inside of 'uib-tabset' and it appears to break. For example:

```
<select chosen class="form-control" data-placeholder="timezone" ng-model="student.timezone" ng-options="name for name in timezones" ng-change="update()">
    <option value=""></option>
</select>
<uib-tabset>
    <uib-tab heading="Timezones> Timezone content </uib-tab>
</uib-tabset>
```

This shows the angular-chosen select perfect and has a tabset beneath it. However, if I move the chosen into the tab content, the chosen stops working (ie, it just shows an empty select). Like so:

```
<uib-tabset>
    <uib-tab heading="Timezones> Timezone content 
        <select chosen class="form-control" data-placeholder="timezone" ng-model="student.timezone" ng-options="name for name in timezones" ng-change="update()">
            <option value=""></option>
        </select>
    </uib-tab>
</uib-tabset>
```

At first I thought it might not like nested directives, but I have several other directives that work fine within uib-tabset. If you had any thoughts, that'd be greatly appreciated and if you can point me in the right direction, I'm happy to take a crack at it myself.
Thanks!

**Comment by adityasharat** [comment]
Can you try this once ?

``` html
<uib-tabset>
    <uib-tab heading="Timezones> Timezone content 

        <select chosen options="timezones"
                     class="form-control" 
                     data-placeholder="timezone" 
                     ng-model="student.timezone" 
                     ng-options="name for name in timezones" ng-change="update()">
            <option value=""></option>
        </select>

    </uib-tab>
</uib-tabset>
```

`options` attribute was missing. This might have been the issue. Let me know, if it doesn't work. 

And Thank You :smiley:

**Comment by jonathanboswell** [comment]
Thanks for getting back to me! So adding the "options" value didn't solve the issue. I've done a lot of digging around and I think it might be tied to the 'restrict' value on the directive. It looks like when used in conjunction with just $scope it loses synch. I created a Plunkr to demonstrate the various $scope use cases:

http://plnkr.co/edit/qBjsswQimx9ebrfbp2hv?p=preview
(view in Firefox...for some reason Chrome doesn't like it)

Perhaps I should only use it with named controllers or $scope objects?

**Comment by adityasharat** [comment]
I think you are right. Using it without a named controller or without wrapping it around a $scope object seems to surface this issue.
I'm guessing, when we set the value in the outer `ng-model="timezone"` the one inside `uibTabset` is just referring to the value in the parent scope. Once it is set, the inner scope creates a `timezone` property of its own and is detached from the parent scopes' `timezone` property.
Maybe primitives are passed by value to the child scope. (Are `string` primitives, immutable :confounded: ?)

As of now, use a named controller or $scope object.
I will dig in and figure out if it's an issue with the directive or if it's just how Angular works.

**Comment by adityasharat** [comment]
This is how angular works apparently. Closing the issue.
