### ISSUE TITLE
Add Bower Support

### ISSUE THREAD

**Issue by jmelosegui** [adityasharat/angular-chosen#16]
I Cannot find this lib on bower. Could you add support for it?

**Comment by aliakhtar** [comment]
+1

**Comment by adityasharat** [comment]
Added support for angular-chosen on bower
angular-chosen-js
:+1:

**Comment by jmelosegui** [comment]
It would be nice if you also update the readme. Something like:

**Install with Bower**

```
bower install angular-chosen-js
```

Any way, I cannot see it yet. http://bower.io/search/?q=angular-chosen-js

**Comment by adityasharat** [comment]
Yeah, it is not coming the search.
just try
`bower install angular-chosen-js`

will update the readme
