### ISSUE TITLE
Problem when the ng-model is initialized

### ISSUE THREAD

**Issue by Isaac6702** [adityasharat/angular-chosen#19]
in a multiple selection list if ng-model is initialized, the component does not load the starting value found in the ng-model
    <select chosen multiple
            ng-model="user.sportsPreferences"
            ng-options="sportsPreference as sportsPreference.name
      for sportsPreference in sportsPreferences">
    </select>

**Comment by adityasharat** [comment]
Hey @Isaac6702,
If you initialize `ng-model` with an array of `objects` (not primitives) angular will not be able to set the initial values for you for the same reason as the following:

``` javascript
var a = {};
var b = {};

a === b; // false
```

By default objects are tracked by using the hash of the object in angular. You should use `track by sportsPreference.someUniqueKey` in the `ng-options` directive to fix your issue. example:

``` html
<select chosen multiple
  ng-model="user.sportsPreferences" 
  ng-options="sportsPreference as sportsPreference.name for sportsPreference in sportsPreferences track by sportsPreference.id">
```

where `id` is the unique key in `sportsPreference`

Please let me know if this fixes your issue.

**Comment by Isaac6702** [comment]
@adityasharat  thanks for your prompt response,

you're absolutely right, I helped.

But now I can think of another problem the sportsPreferences variable is carried right through an even restfull call and the call takes a long field I always appears empty. No it is this should.

I would greatly appreciate the help.

**Comment by adityasharat** [comment]
try this

``` html
<select chosen multiple options="sportsPreferences"
  ng-model="user.sportsPreferences" 
  ng-options="sportsPreference as sportsPreference.name for sportsPreference in sportsPreferences track by sportsPreference.id">
```

add the `options` attribute.

**Comment by Isaac6702** [comment]
@adityasharat  thank you very much for the help, it works perfect
