### ISSUE TITLE
event on-select and $item

### ISSUE THREAD

**Issue by Isaac6702** [adityasharat/angular-chosen#20]
Hi,
As I can trigger an event when something of a "Standard Select" is selected and know the item that was selected.

Is there any on-select = "function ($ item)" event

**Comment by adityasharat** [comment]
Add a watch to the `ng-model` in your `controller`

``` html
<select chosen ng-model="data.selected">
```

``` javascript
$scope.$watch('data.selected', function () {
  // handle the change
});
```

or use `ng-change`

``` html
<select chosen ng-model="data.selected" ng-change="myMethod(data.selected)">
```

**Comment by Isaac6702** [comment]
Perfect, thanks
