### ISSUE TITLE
clarify relation to leocaseiro/angular-chosen

### ISSUE THREAD

**Issue by madmas** [adityasharat/angular-chosen#26]
Hi, 
I noticed that there is also [leocaseiro/angular-chosen](https://github.com/leocaseiro/angular-chosen). 
To make it easier for users to picker the library best for their use case, it would be helpful if you can add a section that  exaplains the relation or differences of the libraries to the README.

thanks a lot :)

**Comment by adityasharat** [comment]
@madmas There aren't too many differences in terms of features or support. Relation is that they exactly the same thing.

Notables differences once are:
- support for `ngOptions` without the extra `options` attribute.
- loading state animation when `options` is an unresolved promise.
- We lacks the documentation, readme, and followers compared to leocaseiro's.

If you still feel there is a requirement to add this to the readme, please do raise a PR.
I assume there are many more Angular Chosen implementation out there :)

**Comment by adityasharat** [comment]
Closing
