### ISSUE TITLE
iElm.chosen is not a function

### ISSUE THREAD

**Issue by EddyTheDove** [adityasharat/angular-chosen#29]
![screen shot 2016-07-30 at 9 30 10 am](https://cloud.githubusercontent.com/assets/8747601/17266148/50ec9d18-5638-11e6-80e0-35ce5cd6bddf.png)
TypeError: iElm.chosen is not a function

**Comment by adityasharat** [comment]
Can you tell me which version of `angular` you are using; or better yet, share a [fiddle](https://jsfiddle.net)
in the interim can you try droping the `=""` in `chosen=""`

**Comment by EddyTheDove** [comment]
I'm using AngularJS v1.5.7 using bower, and gulp to compile and concatenate all my JS vendors.

**Comment by EddyTheDove** [comment]
It's working now. I just added chosen.js in my scripts. Since it wasn't specified, I did not know I should have added it. Obviously, it's a dependency, but I somehow assumed you were this package was loading it already.

**Comment by adityasharat** [comment]
👍
