### ISSUE TITLE
Model not updating after API load

### ISSUE THREAD

**Issue by brendt** [adityasharat/angular-chosen#3]
I'm having an issue with a multiple select when editting an entity in my application. 

In my application, I can edit a material which has multiple categories. When creating a new material (this is the same form in HTML), it's possible to add categories and these are saved to the database. However: when editting a material, selected categories are loaded from the API seperatly, and stored in a scope variable, but the chosen select remains empty. 

Am I missing something?

``` javascript
$scope.selectedcategories = [];
API.get('api/v1/material/' + id + '/category').then(function (response) {
    $scope.selectedcategories = response.data;
});
```

``` html
<select chosen multiple
        name="category"
        id="category"
        ng-model="selectedcategories"
        options="categories"
        ng-options="category.name for category in categories">
</select>
```

**Comment by brendt** [comment]
Seems I missed something. You've got to specify which field to bind the model to using `as`, and also the selection array should be an array of values, not objects. eg. an array of IDs.

``` javascript
// the selected category IDs
$scope.selectedcategories = [1,2,3];
```

``` html
<select chosen multiple
        name="category"
        id="category"
        ng-model="selectedcategories"
        options="categories"
        ng-options="category.id as category.name for category in categories">
</select>
```

**Comment by adityasharat** [comment]
If you want to set the selected values as objects try this.

``` html
<select chosen multiple
        name="category"
        id="category"
        ng-model="selectedcategories"
        options="categories"
        ng-options="category as category.name for category in categories">
</select>
```
