### ISSUE TITLE
Search Not Working

### ISSUE THREAD

**Issue by ubaid-rehman** [adityasharat/angular-chosen#35]
I am getting this error when I enter search key

chosen.jquery.js?t=1:386 Uncaught TypeError: this.results_search is not a function(…)AbstractChosen.keyup_checker @ chosen.jquery.js?t=1:386(anonymous function) @ chosen.jquery.js?t=1:601dispatch @ jquery.min.js:4r.handle @ jquery.min.js:4

my code is
js:
	$scope.libraries = [
	                    {id: "1", label: "Label 1"},
	                    {id: "2", label: "Label 2"},
	                    {id: "3", label: "Label 3"},
	                    {id: "4", label: "Label 4"}
	                    ];
	$scope.selectedLibraries = [];
html:
		<select 
			placeholder-text-multiple="Libraries" chosen multiple options="libraries" 
			ng-model="selectedLibraries" ng-options="lib.id as lib.label for lib in libraries">
		</select>

['angular.chosen'] added as a dependency in the module.

chosen.jquery.js
chosen.css
angular-chosen.js

these files added

**Comment by adityasharat** [comment]
@ubaid-rehman This may be too late.
Can you share the HTML/template where you used chosen.

**Comment by ubaid-rehman** [comment]
I found out the real problem. I was using chosen.jquery version 1.5.1, there was no function named result_search, I reverted to version 1.4.2 and the problem is solved. Thanks for your time.
