### ISSUE TITLE
Updating data list on Angularjs is not reflecting in Frontend

### ISSUE THREAD

**Issue by nesticle8bit** [adityasharat/angular-chosen#37]
Hi guys, I have a little problem, everytime I update the data list in my controller is doesnt reflect the change in frontend, im doing this.

In this function I just want to remove an item in a list if its added in the table, but the change is not 'working'

```javascript
$scope.checkNoNormasDerogadaReglamentada = function (id_norma, listaDatos) {
        var count = listaDatos.length;

        for (var i = 0; i < count; i++)
        {
            if (id_norma == listaDatos[i].Id)
            {
                listaDatos.splice(i, 1);
                break;
            }
        }
    }
```
![Video](https://puu.sh/vvZzx/10127557d3.gif "Video")

I did this but it doesnt work

```javascript
$('select[chosen]').trigger('chosen:updated');
```

This is my Html

```html
<select chosen options="listaNormasAll" class="form-control" ng-model="norma.reglamentaNorma" ng-options="item as item.Nombre for item in listaNormasAll">
                                <option value="">---</option>
                            </select>
```

**Comment by adityasharat** [comment]
I hope `listaDatos` is attached to the `$scope` or `this` of the controller.
or just change it to this: (if this makes sense in your use case)

```javascript
$scope.checkNoNormasDerogadaReglamentada = function (id_norma) {
        var count = listaDatos.length;

        for (var i = 0; i < count; i++)
        {
            if (id_norma == $scope. listaNormasAll[i].Id)
            {
                $scope.listaNormasAll.splice(i, 1);
                break;
            }
        }
    }
```

If that doesn't work; is the entire UI under the same controller? If not that could also be the issue. Maybe the digest cycle was never triggered on the other controller and only when you clicked the drop did it execute the digest cycle and it got updated. Try `$rootScope.$apply()`. Not sure if that will work either.

**Comment by nesticle8bit** [comment]
Omg thank you so much, that works for me!

**Comment by adityasharat** [comment]
Happy to help. Closing this issue. :)
