### ISSUE TITLE
Pulling data to chosen

### ISSUE THREAD

**Issue by jtmurphree** [adityasharat/angular-chosen#6]
I am working on a project where we are trying to use chosen for a filter drop down. We have the list set up and are sucessfully pulling data to the list box. However, when we implement chosen we can still see the data in the DOM but we get nothing in the chosen list. Is anyone familiar with this? Is this a possible bug or am I just doing something wrong?

**Comment by adityasharat** [comment]
Hey @jtmurphree 
Can you share the markup of the list where you used the directive? It should be something like this:

``` HTML
<select chosen 
        options="properties"
        ng-model="property.name"
        ng-options="p.name as p.name for p in properties">
</select>
```

Make sure you add the `options` attribute. If you are using `options` and still facing an issue:
- is the `options` attribute a promise?
- can you share a sample json of the data?

**Comment by jtmurphree** [comment]
actualy turns out it was rendering before the data was populated. We have solved the problem. Thank you.
