### ISSUE TITLE
Is it possible to search by Id and the name

### ISSUE THREAD

**Issue by yasir095** [adityasharat/angular-chosen#9]
Hi, I am using angular chosen for one of my project. There is a selection box where I got few products I am displaying with chosen Select plugin, they can be searched by name at the moment. But I need it to work with productId as well. So what I need is to be able to search the product by name as well as Id. Is it possible to achieve that using this directive.

Let say my product object looks like this 

[
  {
    "productId": 11,
    "name": "Bananas"
  },
  {
    "productId": 22,
    "name": "oranges"
  }
]

Please have a look thanks.

**Comment by adityasharat** [comment]
That would be very nice add on. But It seems to be out of scope for [angular-chosen](https://github.com/harvesthq/chosen). If it can be added to chosen then we could expose an attribute in the directive to specify what key to search by.

**Comment by adityasharat** [comment]
Closing the issue.
